version: '3.8'
services:
  database:
    image: 'postgres:12.3'
    ports:
      - '9000:5432'
    container_name: coffee_db_container
    environment:
      POSTGRES_USER: coffee_db_technical_user
      POSTGRES_PASSWORD: coffeedb
      POSTGRES_DB: coffee_db
    volumes:
      - ./sql/start.sql:/docker-entrypoint-initdb.d/1-start.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./sql/Extra.sql:/docker-entrypoint-initdb.d/3-Extra.sql
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    environment:
      - FLASK_APP=backend.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://coffee_db_technical_user:coffeedb@database:9000/coffee_db
    depends_on:
      - database